version: "3.8"

services:
  spark-master:
    image: ${SPARK_IMAGE_NAME}:${SPARK_IMAGE_TAG}
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"    # Spark master port
      - "8080:8080"    # Spark web UI
    networks:
      - kafka-net

  spark-worker-1:
    image: ${SPARK_IMAGE_NAME}:${SPARK_IMAGE_TAG}
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

    volumes:
      - ${PWD}/spark:/opt/spark_jobs
      - ${PWD}/scripts:/opt/scripts
      - ${PWD}/data:/data
    env_file:
      - ../../.env.development
    depends_on:
      - spark-master
    networks:
      - kafka-net

  spark-worker-2:
    image: ${SPARK_IMAGE_NAME}:${SPARK_IMAGE_TAG}
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

    volumes:
      - ${PWD}/spark:/opt/spark_jobs
      - ${PWD}/scripts:/opt/scripts
      - ${PWD}/data:/data
    env_file:
      - ../../.env.development
    depends_on:
      - spark-master
    networks:
      - kafka-net

  spark-worker-3:
    image: ${SPARK_IMAGE_NAME}:${SPARK_IMAGE_TAG}
    container_name: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

    volumes:
      - ${PWD}/spark:/opt/spark_jobs
      - ${PWD}/scripts:/opt/scripts
      - ${PWD}/data:/data
    env_file:
      - ../../.env.development
    depends_on:
      - spark-master
    networks:
      - kafka-net

  spark-streaming: #always-on container (streaming data)
    image: ${SPARK_IMAGE_NAME}:${SPARK_IMAGE_TAG}
    container_name: spark-streaming
    command: ["python", "main.py", "--job", "streaming"]
    environment:
      - PYSPARK_SUBMIT_ARGS=--master spark://spark-master:7077 pyspark-shell

    env_file:
      - ../../.env.development
    volumes:
      - ${PWD}/spark:/opt/spark_jobs
      - ${PWD}/scripts:/opt/scripts
      - ${PWD}/data:/data
    working_dir: /opt/spark_jobs
    restart: always
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
      - spark-worker-3
    networks:
      - kafka-net

networks:
  kafka-net:
    external: true