# docker-compose.yml
services:
  dashboard:
    build:
      context: ../..                     # project root
      dockerfile: docker/streamlit/Dockerfile
    working_dir: /app
    volumes:
      - ../..:/app                       # mount project root → /app
    ports:
      - "8510:8504"                      # use a free host port
    environment:
      MONGO_URI: "mongodb://admin:pass@mongodb:27017/?authSource=admin"
      MONGO_DB: "podcasts"
      MONGO_COLLECTION_FINAL_RECS: "final_recommendations"
      # Delta paths inside the container (bind-mounted project)
      DELTA_EVENTS_PATH: "/app/_delta/events"
      DELTA_PATH_EPISODES: "/app/_delta/episodes"
      # avoid AWS IMDS calls on laptops
      AWS_EC2_METADATA_DISABLED: "true"
    command: >
      streamlit run dashboard.py --server.port 8504 --server.address 0.0.0.0
    restart: unless-stopped
