version: "3.8"

services:

  spark-streaming:
    image: ${SPARK_IMAGE_NAME}:${SPARK_IMAGE_TAG}
    container_name: spark-streaming
    command: >
      spark-submit
      --master local[*]
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.6,io.delta:delta-spark_2.12:3.1.0,org.mongodb.spark:mongo-spark-connector_2.12:10.3.0
      /opt/project/spark/pipelines/streaming_user_events_pipeline.py
    environment:
      - PYTHONPATH=/opt/project
      - PYSPARK_PYTHON=python3
      - SPARK_SUBMIT_OPTS=-XX:+UseG1GC -Duser.timezone=UTC
    env_file:
      - ../../.env.development
    volumes:
      - ${PWD}:/opt/project
      - ${PWD}/data:/data
    depends_on:
      - spark-master
      - spark-worker-1
    networks:
      - kafka-net

networks:
  kafka-net:
    external: true
    name: kafka-net

